### ISSUE TITLE
User Story 1: Start a Planning Poker Session

### ISSUE THREAD

**Issue by lrluque** [JM-Rib/sds2#6]
As a Scrum Master I want to start a new Planning Poker session so that I can facilitate estimation with my team.

**Acceptance Criteria:**

1.     When I start a new session, then a unique session ID is generated.
2.     When I start a new session, then I can invite team members via a link.
3.     When team members join the session, their names are displayed in the session lobby.

# Planning Poker Session - Tasks Breakdown

## Task 1: Start a New Session
- [x] **Generate a unique session ID**  
  - [x] #45
  - [x] #46
  - [x] #73

---

## Task 2: Generate an Invitation Link
- [x] **Create a unique invitation link**  
  - [x] #47
  - [x] #48

---

## Task 3: Handle Team Member Invitations
- [x] **Enable team members to join via invitation link**  
  - [x] #49
  - [x] #50

---

## Task 4: Testing and Quality Assurance
- [ ] **Ensure robust functionality through testing**  
  - [x] #54
  - [x] #55
  - [x] #56

---

**Comment by lrluque** [comment]
We are going to use jwt tokens for the sessions for now. I intend to make it a little bit more sophisticated. Mostly because the link of each room is very large and I'd like a shorter one.

**Comment by lrluque** [comment]
TO-DO:

- [ ] When someone enters the room, his name is displayed on the board with the first letter of both name and surname.
- [ ] When someone press a number, it a appears next to his name.
